name: SpaceMarket Frontend CI/CD

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - front/**        

pr:
  branches:
    include:
      - main
  paths:
    include:
      - front/**

pool:
  name: 'Newpool'     

stages:
- stage: Build
  displayName: Build Angular Frontend
  jobs:
  - job: BuildFrontend
    displayName: Build Angular App
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '20.x'
        
    - script: |
        cd front
        npm install
        npm run build --configuration production
      displayName: 'npm install and build'
      
    - task: CopyFiles@2
      displayName: 'Copy dist files'
      inputs:
        SourceFolder: 'front/dist/front/browser'  
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'spacemarket-front'

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployFrontend
    displayName: Deploy Angular to Azure
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'spacemarket-front'
        downloadPath: '$(Pipeline.Workspace)'
        
    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'azure-service-connection' 
        appType: 'webAppLinux'
        appName: 'spacemarket-front' 
        package: '$(Pipeline.Workspace)/spacemarket-front'
        runtimeStack: 'NODE|20-lts'