name: SpaceMarket Frontend CI/CD

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - front/**
pool:
  name: 'Newpool'

stages:
- stage: Deploy
  displayName: Build and Deploy to Azure SWA
  jobs:
  - job: DeployJob
    displayName: Deploy Angular
    steps:
    - checkout: self
      submodules: true

    - task: AzureStaticWebApp@0
      displayName: 'Build and Deploy SWA'
      inputs:
        app_location: '/front'            
        api_location: ''                  
        output_location: 'dist/front/browser' 
        azure_static_web_apps_api_token: $(SWA_TOKEN)