spring.application.name=local
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configuration principale commune
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration Liquibase désactivée par défaut, activée par profil
# spring.liquibase.enabled=false
# spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml