name: SpaceMarket Frontend CI/CD

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - front/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - front/*

jobs:
- job: build_frontend
  displayName: 'Build and Deploy React Frontend'
  pool: Newpool
  variables:
  - group: Azure-Static-Web-Apps-icy-desert-079fdf40f-variable-group
  steps:
  - checkout: self
  
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_DESERT_079FDF40F)
      app_location: "/front" 
      api_location: ""
      output_location: "build"
    env:
      ENABLE_ORYX_BUILD: true
      WEBSITE_NODE_DEFAULT_VERSION: "~20" 